// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWmUuNIJ38RRIjYechCtALKz1fVlQqeQ',
    appId: '1:125409505279:web:d2f40f89ca8d8ecdcac1ca',
    messagingSenderId: '125409505279',
    projectId: 'clothwik-7b0ab',
    authDomain: 'clothwik-7b0ab.firebaseapp.com',
    storageBucket: 'clothwik-7b0ab.appspot.com',
    measurementId: 'G-GBG6D8V5B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_73OB0NkVRVctKhM71zD14qwm-XJmmVk',
    appId: '1:125409505279:android:6f3a501fdd20dfa4cac1ca',
    messagingSenderId: '125409505279',
    projectId: 'clothwik-7b0ab',
    storageBucket: 'clothwik-7b0ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3G6NQExFr87n06qRAbywnHOagY5UfIIY',
    appId: '1:125409505279:ios:0a9e212ecf328fa8cac1ca',
    messagingSenderId: '125409505279',
    projectId: 'clothwik-7b0ab',
    storageBucket: 'clothwik-7b0ab.appspot.com',
    iosBundleId: 'com.shop.clothwik',
  );
}
